using TradingPulse.Application.Abstractions;
using TradingPulse.Application.Models;
using TradingPulse.Domain;
using TradingPulse.Domain.Enums;
using TradingPulse.Infrastructure.Orders;
using TradingPulse.Infrastructure.Pricing;
using TradingPulse.Infrastructure.Rules;
using TradingPulse.Infrastructure.Trading;

namespace TradingPulse.Infrastructure.Tests;

/// <summary>
/// Covers the idempotent-retry behavior added to <see cref="OrderSubmissionService"/>:
/// an identical resubmission of a <see cref="ClientOrderId"/> returns the original
/// decision without re-evaluating or persisting, while a *conflicting* reuse of the
/// same id (different order details) still goes through the duplicate-id rule.
/// </summary>
public class OrderSubmissionServiceTests
{
    private readonly InMemoryOrderRepository _orderRepository = new();
    private readonly InMemoryPriceStateRepository _priceStateRepository = new();
    private readonly InMemoryTradingRulesRepository _rulesRepository = new();
    private readonly InMemoryRecentOrderActivity _recentOrderActivity = new();
    private readonly InMemoryClientOrderIdReservationStore _reservationStore = new();
    private readonly OrderSubmissionService _service;

    public OrderSubmissionServiceTests()
    {
        _service = new OrderSubmissionService(
            _priceStateRepository, _rulesRepository, new TradingRulesEngine(), _orderRepository, _recentOrderActivity, _reservationStore);
    }

    [Fact]
    public async Task SubmitAsync_Accepts_And_Persists_NewOrder()
    {
        await SeedPriceAsync("EURUSD", 1.10m);
        var order = CreateOrder("ORD-1", price: 1.10m, quantity: 100m);

        var decision = await _service.SubmitAsync(order);

        Assert.Equal(DecisionStatus.Accepted, decision.Status);
        var stored = await _orderRepository.GetByClientOrderIdAsync("ORD-1");
        Assert.NotNull(stored);
        Assert.Equal(order.Id, stored!.Order.Id);

        // Also lands in the bounded in-memory cache the dashboard reads from (IRecentOrderActivity)
        // - not just the durable repository.
        Assert.Contains(_recentOrderActivity.GetRecent(10), e => e.Order.Id == order.Id);
    }

    [Fact]
    public async Task SubmitAsync_IdenticalRetry_ReturnsOriginalDecision_WithoutPersistingAgain()
    {
        await SeedPriceAsync("EURUSD", 1.10m);
        var first = CreateOrder("ORD-2", price: 1.10m, quantity: 100m);
        var firstDecision = await _service.SubmitAsync(first);

        // Same ClientOrderId, same Symbol/Side/Type/Price/Quantity - a genuine retry
        // (e.g. the client never saw the first response), just a different Order.Id/timestamp.
        var retry = CreateOrder("ORD-2", price: 1.10m, quantity: 100m);
        var retryDecision = await _service.SubmitAsync(retry);

        Assert.Equal(firstDecision.Id, retryDecision.Id);
        Assert.Equal(firstDecision.OrderId, retryDecision.OrderId);
        Assert.NotEqual(retry.Id, retryDecision.OrderId); // decision still points at the original order, not the retry

        var history = await _orderRepository.GetHistoryAsync(new Application.Models.OrderHistoryFilter(Symbol: "EURUSD"));
        Assert.Single(history); // no second row written for the retry
    }

    [Fact]
    public async Task SubmitAsync_ConflictingReuse_OfClientOrderId_IsRejected_AndPersistedSeparately()
    {
        await SeedPriceAsync("EURUSD", 1.10m);
        var first = CreateOrder("ORD-3", price: 1.10m, quantity: 100m);
        await _service.SubmitAsync(first);

        // Same ClientOrderId, but a different Price - not a retry of the same request, so it
        // must not be silently treated as one; the duplicate-id rule rejects it.
        var conflicting = CreateOrder("ORD-3", price: 1.101m, quantity: 100m);
        var decision = await _service.SubmitAsync(conflicting);

        Assert.Equal(DecisionStatus.Rejected, decision.Status);
        Assert.Contains(decision.RejectionReasons, r => r.Code == RejectionReasonCode.DuplicateClientOrderId);

        var history = await _orderRepository.GetHistoryAsync(new Application.Models.OrderHistoryFilter(Symbol: "EURUSD"));
        Assert.Equal(2, history.Count); // the conflicting attempt is persisted as its own (rejected) entry
    }

    [Fact]
    public async Task SubmitAsync_AutoGeneratedOrder_SkipsClientOrderIdLookup()
    {
        await SeedPriceAsync("EURUSD", 1.10m);
        var countingOrderRepository = new CountingOrderRepository(_orderRepository);
        var service = new OrderSubmissionService(
            _priceStateRepository, _rulesRepository, new TradingRulesEngine(), countingOrderRepository, _recentOrderActivity, _reservationStore);
        var order = Order.CreateAutoGenerated("EURUSD", OrderSide.Sell, price: 1.10m, quantity: 10m, submittedAt: DateTimeOffset.UtcNow);

        var decision = await service.SubmitAsync(order);

        Assert.Equal(DecisionStatus.Accepted, decision.Status);
        // The synthesized "AUTO-{guid}" ClientOrderId can never collide with a prior one, so the
        // lookup that exists purely to support user-submitted idempotency/duplicate-detection
        // must never run for an auto-generated order.
        Assert.Equal(0, countingOrderRepository.GetByClientOrderIdCallCount);
    }

    [Fact]
    public async Task SubmitAsync_UserSubmittedOrder_StillRunsClientOrderIdLookup()
    {
        await SeedPriceAsync("EURUSD", 1.10m);
        var countingOrderRepository = new CountingOrderRepository(_orderRepository);
        var service = new OrderSubmissionService(
            _priceStateRepository, _rulesRepository, new TradingRulesEngine(), countingOrderRepository, _recentOrderActivity, _reservationStore);
        var order = CreateOrder("ORD-4", price: 1.10m, quantity: 100m);

        await service.SubmitAsync(order);

        // Unlike auto-generated orders, a user-chosen ClientOrderId can legitimately repeat (a
        // retry) - the lookup that backs idempotent-replay and the duplicate-id rule must still run.
        Assert.Equal(1, countingOrderRepository.GetByClientOrderIdCallCount);
    }

    [Fact]
    public async Task SubmitAsync_WithRulesArgument_DoesNotRefetchRules()
    {
        await SeedPriceAsync("EURUSD", 1.10m);
        var countingRulesRepository = new CountingTradingRulesRepository(_rulesRepository);
        var service = new OrderSubmissionService(
            _priceStateRepository, countingRulesRepository, new TradingRulesEngine(), _orderRepository, _recentOrderActivity, _reservationStore);
        var rules = await countingRulesRepository.GetCurrentAsync(); // 1 call, matches PriceTickProcessor's own fetch
        var order = CreateOrder("ORD-5", price: 1.10m, quantity: 100m);

        var decision = await service.SubmitAsync(order, rules);

        Assert.Equal(DecisionStatus.Accepted, decision.Status);
        // Only the one call this test made itself - SubmitAsync(order, rules, ct) must not fetch
        // its own copy, which is the whole point of the overload (see PriceTickProcessor).
        Assert.Equal(1, countingRulesRepository.GetCurrentAsyncCallCount);
    }

    [Fact]
    public async Task SubmitAsync_NewOrder_ClaimsReservation()
    {
        await SeedPriceAsync("EURUSD", 1.10m);
        var order = CreateOrder("ORD-6", price: 1.10m, quantity: 100m);

        await _service.SubmitAsync(order);

        // Trying to claim the same id again must fail and report the order we just submitted as
        // the owner - proof SubmitAsync actually claimed it, not just persisted the order.
        var reservation = await _reservationStore.TryReserveAsync("ORD-6", Guid.NewGuid(), Guid.NewGuid());
        Assert.False(reservation.Reserved);
        Assert.Equal(order.Id, reservation.ExistingOrderId);
    }

    [Fact]
    public async Task SubmitAsync_AutoGeneratedOrder_NeverConsultsReservationStore()
    {
        await SeedPriceAsync("EURUSD", 1.10m);
        var countingReservationStore = new CountingReservationStore(_reservationStore);
        var service = new OrderSubmissionService(
            _priceStateRepository, _rulesRepository, new TradingRulesEngine(), _orderRepository, _recentOrderActivity, countingReservationStore);
        var order = Order.CreateAutoGenerated("EURUSD", OrderSide.Sell, price: 1.10m, quantity: 10m, submittedAt: DateTimeOffset.UtcNow);

        await service.SubmitAsync(order);

        // Same reasoning as the ClientOrderId lookup skip: a synthesized "AUTO-{guid}" id can
        // never race with a prior one, so there is nothing for the reservation store to protect.
        Assert.Equal(0, countingReservationStore.TryReserveAsyncCallCount);
    }

    [Fact]
    public async Task SubmitAsync_DuplicateCheckDisabled_NeverConsultsReservationStore()
    {
        await SeedPriceAsync("EURUSD", 1.10m);
        await _rulesRepository.SaveAsync((await _rulesRepository.GetCurrentAsync()) with { DuplicateOrderIdCheckEnabled = false });
        var countingReservationStore = new CountingReservationStore(_reservationStore);
        var service = new OrderSubmissionService(
            _priceStateRepository, _rulesRepository, new TradingRulesEngine(), _orderRepository, _recentOrderActivity, countingReservationStore);
        var order = CreateOrder("ORD-7", price: 1.10m, quantity: 100m);

        await service.SubmitAsync(order);

        // With the rule off, duplicates are allowed by design - reserving a ClientOrderId only
        // to never use it for anything would be a wasted round trip on every submission.
        Assert.Equal(0, countingReservationStore.TryReserveAsyncCallCount);
    }

    [Fact]
    public async Task SubmitAsync_LosesReservationRace_SameRequest_ReplaysWinnersDecision()
    {
        await SeedPriceAsync("EURUSD", 1.10m);
        var raceRepository = new RaceSimulatingOrderRepository(_orderRepository);
        var service = new OrderSubmissionService(
            _priceStateRepository, _rulesRepository, new TradingRulesEngine(), raceRepository, _recentOrderActivity, _reservationStore);

        // The "winner" of the race: already fully persisted and already holds the reservation for
        // this ClientOrderId, simulating a concurrent submission that finished first.
        var winnerOrder = CreateOrder("ORD-RACE-1", price: 1.10m, quantity: 100m);
        var winnerDecision = OrderDecision.Accept(winnerOrder.Id, DateTimeOffset.UtcNow);
        await raceRepository.AddAsync(winnerOrder, winnerDecision);
        await _reservationStore.TryReserveAsync("ORD-RACE-1", winnerOrder.Id, winnerDecision.Id);

        // Our own attempt: identical request details. GetByClientOrderIdAsync is forced to miss
        // (RaceSimulatingOrderRepository), so only the reservation claim below can catch this.
        var ourOrder = CreateOrder("ORD-RACE-1", price: 1.10m, quantity: 100m);

        var decision = await service.SubmitAsync(ourOrder);

        Assert.Equal(winnerDecision.Id, decision.Id); // replayed the winner's decision, not a new one

        var history = await _orderRepository.GetHistoryAsync(new OrderHistoryFilter(Symbol: "EURUSD"));
        Assert.Single(history); // our losing attempt was never persisted
    }

    [Fact]
    public async Task SubmitAsync_LosesReservationRace_ConflictingRequest_IsRejected_AndPersistedSeparately()
    {
        await SeedPriceAsync("EURUSD", 1.10m);
        var raceRepository = new RaceSimulatingOrderRepository(_orderRepository);
        var service = new OrderSubmissionService(
            _priceStateRepository, _rulesRepository, new TradingRulesEngine(), raceRepository, _recentOrderActivity, _reservationStore);

        var winnerOrder = CreateOrder("ORD-RACE-2", price: 1.10m, quantity: 100m);
        var winnerDecision = OrderDecision.Accept(winnerOrder.Id, DateTimeOffset.UtcNow);
        await raceRepository.AddAsync(winnerOrder, winnerDecision);
        await _reservationStore.TryReserveAsync("ORD-RACE-2", winnerOrder.Id, winnerDecision.Id);

        // Different price - a conflicting reuse discovered only via the race, not via the (forced
        // to miss) lookup.
        var ourOrder = CreateOrder("ORD-RACE-2", price: 1.101m, quantity: 100m);

        var decision = await service.SubmitAsync(ourOrder);

        Assert.Equal(DecisionStatus.Rejected, decision.Status);
        Assert.Contains(decision.RejectionReasons, r => r.Code == RejectionReasonCode.DuplicateClientOrderId);

        var history = await _orderRepository.GetHistoryAsync(new OrderHistoryFilter(Symbol: "EURUSD"));
        Assert.Equal(2, history.Count); // winner's row + our own rejected row, same as the non-racy conflicting-reuse case
    }

    private async Task SeedPriceAsync(string symbol, decimal midPrice)
    {
        // Bid/ask straddling midPrice by a cent keeps CurrentMarketPrice == midPrice for these tests.
        PriceUpdate.TryCreate(symbol, midPrice - 0.001m, midPrice + 0.001m, DateTimeOffset.UtcNow, out var tick, out _);
        await _priceStateRepository.ApplyTickAsync(tick);
    }

    private static Order CreateOrder(string clientOrderId, decimal price, decimal quantity, string symbol = "EURUSD") =>
        Order.CreateUserSubmitted(clientOrderId, symbol, OrderSide.Buy, OrderType.Limit, price, quantity, DateTimeOffset.UtcNow);

    /// <summary>Wraps <see cref="IOrderRepository"/> to count <see cref="GetByClientOrderIdAsync"/> calls, for asserting the auto-generated-order skip actually skips.</summary>
    private sealed class CountingOrderRepository(IOrderRepository inner) : IOrderRepository
    {
        public int GetByClientOrderIdCallCount { get; private set; }

        public Task AddAsync(Order order, OrderDecision decision, CancellationToken cancellationToken = default) =>
            inner.AddAsync(order, decision, cancellationToken);

        public Task<OrderHistoryEntry?> GetByClientOrderIdAsync(string clientOrderId, CancellationToken cancellationToken = default)
        {
            GetByClientOrderIdCallCount++;
            return inner.GetByClientOrderIdAsync(clientOrderId, cancellationToken);
        }

        public Task<OrderHistoryEntry?> GetByOrderIdAsync(Guid orderId, CancellationToken cancellationToken = default) =>
            inner.GetByOrderIdAsync(orderId, cancellationToken);

        public Task<IReadOnlyList<OrderHistoryEntry>> GetHistoryAsync(OrderHistoryFilter filter, CancellationToken cancellationToken = default) =>
            inner.GetHistoryAsync(filter, cancellationToken);

        public Task<IReadOnlyList<OrderHistoryEntry>> GetBySymbolAsync(string symbol, CancellationToken cancellationToken = default) =>
            inner.GetBySymbolAsync(symbol, cancellationToken);
    }

    /// <summary>Wraps <see cref="ITradingRulesRepository"/> to count <see cref="GetCurrentAsync"/> calls, for asserting the rules-argument overload doesn't refetch.</summary>
    private sealed class CountingTradingRulesRepository(ITradingRulesRepository inner) : ITradingRulesRepository
    {
        public int GetCurrentAsyncCallCount { get; private set; }

        public Task<TradingRules> GetCurrentAsync(CancellationToken cancellationToken = default)
        {
            GetCurrentAsyncCallCount++;
            return inner.GetCurrentAsync(cancellationToken);
        }

        public Task SaveAsync(TradingRules rules, CancellationToken cancellationToken = default) =>
            inner.SaveAsync(rules, cancellationToken);
    }

    /// <summary>Wraps <see cref="IClientOrderIdReservationStore"/> to count <see cref="TryReserveAsync"/> calls, for asserting when the reservation store is (and isn't) consulted.</summary>
    private sealed class CountingReservationStore(IClientOrderIdReservationStore inner) : IClientOrderIdReservationStore
    {
        public int TryReserveAsyncCallCount { get; private set; }

        public Task<ClientOrderIdReservationResult> TryReserveAsync(
            string clientOrderId, Guid orderId, Guid decisionId, CancellationToken cancellationToken = default)
        {
            TryReserveAsyncCallCount++;
            return inner.TryReserveAsync(clientOrderId, orderId, decisionId, cancellationToken);
        }
    }

    /// <summary>
    /// Forces <see cref="GetByClientOrderIdAsync"/> to always miss, simulating a read that happens
    /// before a concurrent writer's row becomes visible - lets a test drive OrderSubmissionService
    /// into its reservation-based race-resolution path deterministically, without real threads.
    /// </summary>
    private sealed class RaceSimulatingOrderRepository(IOrderRepository inner) : IOrderRepository
    {
        public Task AddAsync(Order order, OrderDecision decision, CancellationToken cancellationToken = default) =>
            inner.AddAsync(order, decision, cancellationToken);

        public Task<OrderHistoryEntry?> GetByClientOrderIdAsync(string clientOrderId, CancellationToken cancellationToken = default) =>
            Task.FromResult<OrderHistoryEntry?>(null);

        public Task<OrderHistoryEntry?> GetByOrderIdAsync(Guid orderId, CancellationToken cancellationToken = default) =>
            inner.GetByOrderIdAsync(orderId, cancellationToken);

        public Task<IReadOnlyList<OrderHistoryEntry>> GetHistoryAsync(OrderHistoryFilter filter, CancellationToken cancellationToken = default) =>
            inner.GetHistoryAsync(filter, cancellationToken);

        public Task<IReadOnlyList<OrderHistoryEntry>> GetBySymbolAsync(string symbol, CancellationToken cancellationToken = default) =>
            inner.GetBySymbolAsync(symbol, cancellationToken);
    }
}
