using TradingPulse.Domain;
using TradingPulse.Domain.Enums;
using TradingPulse.Infrastructure.Trading;

namespace TradingPulse.Infrastructure.Tests;

public class SpreadBasedAutoTradingServiceTests
{
    private readonly SpreadBasedAutoTradingService _service = new();

    private const decimal Threshold = 0.5m;

    [Fact]
    public void TryCreateOrder_ReturnsNull_WhenNoPreviousPrice()
    {
        var latest = CreateSnapshot(bid: 99.9m, ask: 100.1m, currentMarketPrice: 100m, spreadPercent: 1.0m, previousMarketPrice: null);

        var order = _service.TryCreateOrder(latest, Threshold);

        Assert.Null(order);
    }

    [Fact]
    public void TryCreateOrder_ReturnsNull_WhenSpreadBelowThreshold()
    {
        var latest = CreateSnapshot(bid: 99.9m, ask: 100.1m, currentMarketPrice: 100m, spreadPercent: 0.1m, previousMarketPrice: 99m);

        var order = _service.TryCreateOrder(latest, Threshold);

        Assert.Null(order);
    }

    [Fact]
    public void TryCreateOrder_ReturnsNull_WhenPriceUnchanged()
    {
        var latest = CreateSnapshot(bid: 99.9m, ask: 100.1m, currentMarketPrice: 100m, spreadPercent: 1.0m, previousMarketPrice: 100m);

        var order = _service.TryCreateOrder(latest, Threshold);

        Assert.Null(order);
    }

    [Fact]
    public void TryCreateOrder_ReturnsSellOrder_WhenPriceIncreased()
    {
        var latest = CreateSnapshot(bid: 99.8m, ask: 100m, currentMarketPrice: 100m, spreadPercent: 1.0m, previousMarketPrice: 99m);

        var order = _service.TryCreateOrder(latest, Threshold);

        Assert.NotNull(order);
        Assert.Equal(OrderSide.Sell, order!.Side);
        Assert.Equal(99.97m, order.Price); // 100 - 100 * 0.03 / 100
        Assert.Equal(100m, order.Quantity); // 10,000 target notional / 100 mid
        Assert.Equal(OrderOrigin.AutoGenerated, order.Origin);
    }

    [Fact]
    public void TryCreateOrder_ReturnsBuyOrder_WhenPriceDecreased()
    {
        var latest = CreateSnapshot(bid: 100m, ask: 100.2m, currentMarketPrice: 100m, spreadPercent: 1.0m, previousMarketPrice: 101m);

        var order = _service.TryCreateOrder(latest, Threshold);

        Assert.NotNull(order);
        Assert.Equal(OrderSide.Buy, order!.Side);
        Assert.Equal(100.03m, order.Price); // 100 + 100 * 0.03 / 100
        Assert.Equal(100m, order.Quantity);
        Assert.Equal(OrderOrigin.AutoGenerated, order.Origin);
    }

    private static PriceSnapshot CreateSnapshot(
        decimal bid, decimal ask, decimal currentMarketPrice, decimal spreadPercent, decimal? previousMarketPrice, string symbol = "EURUSD") =>
        new(symbol, bid, ask, currentMarketPrice, ask - bid, spreadPercent, previousMarketPrice, DateTimeOffset.UtcNow);
}
