using TradingPulse.Domain.Enums;

namespace TradingPulse.Domain;

/// <summary>
/// A trade request, either submitted through the API or generated by the
/// auto-trading logic. Both origins flow through the same validation path.
/// </summary>
public sealed class Order
{
    public Guid Id { get; }
    public string ClientOrderId { get; }
    public string Symbol { get; }
    public OrderSide Side { get; }
    public OrderType Type { get; }
    public decimal Price { get; }
    public decimal Quantity { get; }
    public OrderOrigin Origin { get; }
    public DateTimeOffset SubmittedAt { get; }

    private Order(
        Guid id,
        string clientOrderId,
        string symbol,
        OrderSide side,
        OrderType type,
        decimal price,
        decimal quantity,
        OrderOrigin origin,
        DateTimeOffset submittedAt)
    {
        Id = id;
        ClientOrderId = clientOrderId;
        Symbol = symbol;
        Side = side;
        Type = type;
        Price = price;
        Quantity = quantity;
        Origin = origin;
        SubmittedAt = submittedAt;
    }

    /// <summary>Notional value of this order (Price × Quantity).</summary>
    public decimal Notional => Price * Quantity;

    public static Order CreateUserSubmitted(
        string clientOrderId,
        string symbol,
        OrderSide side,
        OrderType type,
        decimal price,
        decimal quantity,
        DateTimeOffset submittedAt)
        => new(Guid.NewGuid(), clientOrderId, symbol, side, type, price, quantity, OrderOrigin.UserSubmitted, submittedAt);

    /// <summary>Builds a candidate order for the auto-trading flow. The client order id is synthesized since there's no external client.</summary>
    public static Order CreateAutoGenerated(
        string symbol,
        OrderSide side,
        decimal price,
        decimal quantity,
        DateTimeOffset submittedAt)
    {
        var id = Guid.NewGuid();
        return new Order(id, $"AUTO-{id}", symbol, side, OrderType.Limit, price, quantity, OrderOrigin.AutoGenerated, submittedAt);
    }

    /// <summary>Reconstructs an order from persisted state, preserving its original id. Not for minting new orders - use the Create* factories for that.</summary>
    public static Order Rehydrate(
        Guid id,
        string clientOrderId,
        string symbol,
        OrderSide side,
        OrderType type,
        decimal price,
        decimal quantity,
        OrderOrigin origin,
        DateTimeOffset submittedAt)
        => new(id, clientOrderId, symbol, side, type, price, quantity, origin, submittedAt);
}
