using TradingPulse.Application.Abstractions;
using TradingPulse.Application.Models;
using TradingPulse.Domain;
using TradingPulse.Domain.Enums;

namespace TradingPulse.Infrastructure.Trading;

/// <summary>Orchestrates the get-price / check-duplicate / evaluate / persist pipeline. See <see cref="IOrderSubmissionService"/>.</summary>
public sealed class OrderSubmissionService(
    IPriceStateRepository priceStateRepository,
    ITradingRulesRepository tradingRulesRepository,
    ITradingRulesEngine tradingRulesEngine,
    IOrderRepository orderRepository,
    IRecentOrderActivity recentOrderActivity,
    IClientOrderIdReservationStore reservationStore) : IOrderSubmissionService
{
    public async Task<OrderDecision> SubmitAsync(Order order, CancellationToken cancellationToken = default)
    {
        var rules = await tradingRulesRepository.GetCurrentAsync(cancellationToken);
        return await SubmitAsync(order, rules, cancellationToken);
    }

    public async Task<OrderDecision> SubmitAsync(Order order, TradingRules rules, CancellationToken cancellationToken = default)
    {
        // Auto-generated orders carry a freshly-minted ClientOrderId ("AUTO-{guid}") that cannot
        // possibly collide with a prior one - looking it up is a guaranteed-wasted database round
        // trip on the tick hot path. User-submitted orders keep the real lookup: their id is
        // client-chosen and a genuine retry is exactly what idempotent-replay below exists for.
        var existing = order.Origin == OrderOrigin.AutoGenerated
            ? null
            : await orderRepository.GetByClientOrderIdAsync(order.ClientOrderId, cancellationToken);

        if (existing is not null && rules.DuplicateOrderIdCheckEnabled && IsSameRequest(existing.Order, order))
        {
            // Idempotent replay: an identical retry of a request already decided (e.g. the client
            // never saw the original response and resubmitted) returns the original decision
            // instead of evaluating - and persisting - a new one. A reused ClientOrderId with
            // *different* order details is not a retry; it falls through to Evaluate below, where
            // the duplicate-id rule rejects it as before.
            return existing.Decision;
        }

        var currentPrice = await priceStateRepository.GetLatestAsync(order.Symbol, cancellationToken);
        var isDuplicate = existing is not null;
        var decision = tradingRulesEngine.Evaluate(order, rules, currentPrice, isDuplicate);

        // The lookup above and this claim are two separate round trips - a second submission for
        // the same ClientOrderId can land in between them (the lookup finds nothing, but someone
        // else reserves and persists before we get here). Only worth claiming when our own info so
        // far says "new" and the duplicate rule is even enabled - a known conflicting reuse or a
        // disabled rule never needs to touch this store.
        if (order.Origin != OrderOrigin.AutoGenerated && existing is null && rules.DuplicateOrderIdCheckEnabled)
        {
            var reservation = await reservationStore.TryReserveAsync(order.ClientOrderId, order.Id, decision.Id, cancellationToken);
            if (!reservation.Reserved)
            {
                // Lost a genuine race: another submission for this ClientOrderId won the claim
                // between our lookup above and this one. Resolve exactly as the sequential path
                // would have, by fetching the winner and treating it as "existing" from here on.
                //
                // Narrow, accepted gap: the winner's reservation and their own AddAsync below are
                // two separate database writes, not one transaction. If this lookup lands in the
                // sliver of time between those two writes, it can still come back null even though
                // the reservation says a winner exists. Treated as a hard failure rather than
                // silently retried/guessed at - see README Known Limitations.
                var winner = await orderRepository.GetByOrderIdAsync(reservation.ExistingOrderId, cancellationToken)
                    ?? throw new InvalidOperationException(
                        $"Reservation for client order id '{order.ClientOrderId}' points at order " +
                        $"{reservation.ExistingOrderId}, which has no persisted order/decision yet.");

                if (IsSameRequest(winner.Order, order))
                {
                    return winner.Decision;
                }

                decision = tradingRulesEngine.Evaluate(order, rules, currentPrice, isDuplicateClientOrderId: true);
            }
        }

        await orderRepository.AddAsync(order, decision, cancellationToken);
        recentOrderActivity.Record(new OrderHistoryEntry(order, decision));

        return decision;
    }

    private static bool IsSameRequest(Order existing, Order incoming) =>
        string.Equals(existing.Symbol, incoming.Symbol, StringComparison.OrdinalIgnoreCase)
        && existing.Side == incoming.Side
        && existing.Type == incoming.Type
        && existing.Price == incoming.Price
        && existing.Quantity == incoming.Quantity;
}
