using TradingPulse.Application.Abstractions;
using TradingPulse.Application.Models;
using TradingPulse.Domain;
using TradingPulse.Domain.Enums;

namespace TradingPulse.Infrastructure.Trading;

/// <summary>Orchestrates the get-price / check-duplicate / evaluate / persist pipeline. See <see cref="IOrderSubmissionService"/>.</summary>
public sealed class OrderSubmissionService(
    IPriceStateRepository priceStateRepository,
    ITradingRulesRepository tradingRulesRepository,
    ITradingRulesEngine tradingRulesEngine,
    IOrderRepository orderRepository,
    IRecentOrderActivity recentOrderActivity) : IOrderSubmissionService
{
    public async Task<OrderDecision> SubmitAsync(Order order, CancellationToken cancellationToken = default)
    {
        var rules = await tradingRulesRepository.GetCurrentAsync(cancellationToken);
        return await SubmitAsync(order, rules, cancellationToken);
    }

    public async Task<OrderDecision> SubmitAsync(Order order, TradingRules rules, CancellationToken cancellationToken = default)
    {
        // Auto-generated orders carry a freshly-minted ClientOrderId ("AUTO-{guid}") that cannot
        // possibly collide with a prior one - looking it up is a guaranteed-wasted database round
        // trip on the tick hot path. User-submitted orders keep the real lookup: their id is
        // client-chosen and a genuine retry is exactly what idempotent-replay below exists for.
        var existing = order.Origin == OrderOrigin.AutoGenerated
            ? null
            : await orderRepository.GetByClientOrderIdAsync(order.ClientOrderId, cancellationToken);

        if (existing is not null && rules.DuplicateOrderIdCheckEnabled && IsSameRequest(existing.Order, order))
        {
            // Idempotent replay: an identical retry of a request already decided (e.g. the client
            // never saw the original response and resubmitted) returns the original decision
            // instead of evaluating - and persisting - a new one. A reused ClientOrderId with
            // *different* order details is not a retry; it falls through to Evaluate below, where
            // the duplicate-id rule rejects it as before.
            return existing.Decision;
        }

        var currentPrice = await priceStateRepository.GetLatestAsync(order.Symbol, cancellationToken);
        var isDuplicate = existing is not null;
        var decision = tradingRulesEngine.Evaluate(order, rules, currentPrice, isDuplicate);

        await orderRepository.AddAsync(order, decision, cancellationToken);
        recentOrderActivity.Record(new OrderHistoryEntry(order, decision));

        return decision;
    }

    private static bool IsSameRequest(Order existing, Order incoming) =>
        string.Equals(existing.Symbol, incoming.Symbol, StringComparison.OrdinalIgnoreCase)
        && existing.Side == incoming.Side
        && existing.Type == incoming.Type
        && existing.Price == incoming.Price
        && existing.Quantity == incoming.Quantity;
}
