using TradingPulse.Application.Abstractions;
using TradingPulse.Domain;
using TradingPulse.Domain.Enums;

namespace TradingPulse.Infrastructure.Trading;

/// <summary>Spread-based auto-trading order construction. See <see cref="IAutoTradingService"/>.</summary>
public sealed class SpreadBasedAutoTradingService : IAutoTradingService
{
    private const decimal AdjustmentPercent = 0.03m; // fixed per spec, not configurable

    /// <summary>Target notional per auto-order; quantity is derived from it so notional stays roughly constant across instruments at very different price levels.</summary>
    private const decimal TargetNotional = 10_000m;

    public Order? TryCreateOrder(PriceSnapshot latest, decimal spreadPercentThreshold)
    {
        if (latest.PreviousMarketPrice is not decimal previousMarketPrice)
        {
            return null;
        }

        if (latest.SpreadPercent <= spreadPercentThreshold || latest.CurrentMarketPrice == previousMarketPrice)
        {
            return null;
        }

        var quantity = Math.Round(TargetNotional / latest.CurrentMarketPrice, 2, MidpointRounding.AwayFromZero);
        var now = DateTimeOffset.UtcNow;

        return latest.CurrentMarketPrice > previousMarketPrice
            ? Order.CreateAutoGenerated(latest.Symbol, OrderSide.Sell, latest.AskPrice - latest.AskPrice * AdjustmentPercent / 100m, quantity, now)
            : Order.CreateAutoGenerated(latest.Symbol, OrderSide.Buy, latest.BidPrice + latest.BidPrice * AdjustmentPercent / 100m, quantity, now);
    }
}
