namespace TradingPulse.Domain.Enums;

/// <summary>Where an order came from. Both origins go through the same rules-engine validation.</summary>
public enum OrderOrigin
{
    UserSubmitted = 0,
    AutoGenerated = 1,
}
